name: qz_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  badges: ^2.0.1
  barcode_scan2: ^4.1.4
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  client_information: ^2.0.2+2
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  easy_mask: ^2.0.1
  equatable: ^2.0.3
  flutter_barcode_listener: ^0.1.3
  flutter_mobx: ^2.0.6+1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.1
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+2
  mask_text_input_formatter: ^2.3.0
  mobx: ^2.0.7
  native_device_orientation: ^1.1.4
  package_info_plus: ^1.4.2
  path_provider: ^2.0.10
  percent_indicator: ^3.4.0
  progress_indicators: ^1.0.0
  qr_flutter: ^4.0.0
  simple_connection_checker: ^0.2.1
  sqflite: ^2.0.0+4
  scrollable_positioned_list: ^0.3.2
  visibility_detector: ^0.3.2
  kiosk_mode: ^0.1.0
  flutter_tts: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

